name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
         webhook: ${{ secrets.DISCORD_WEBHOOK }}
         status: ${{ job.status }}
         message: |
            Workflow on main branch
            ${{ job.status }}. Build ${{ job.status == 'success' && 'successful' || 'failed' }}.
         content: "Hey <@316911818725392384>"
         title: "deploy"
         description: "Build and deploy to GitHub Pages"
         image: ${{ secrets.EMBED_IMAGE }}
         color: 0x0000ff
         url: "https://github.com/sarisia/actions-status-discord"
         username: GitHub Actions
         avatar_url: ${{ secrets.AVATAR_URL }}

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
