            - name: Actions Status Discord
  # You may pin to the exact commit or the version.
  # uses: sarisia/actions-status-discord@8b35962ad57c30272ae149c9ee193887b39e1b69
  uses: sarisia/actions-status-discord@v1.14.0
  with:
    # Discord webhook endpoint. If not set, env.DISCORD_WEBHOOK will be used.
    webhook: # optional
    # Job status. Should be bound to job.status. Default to success.
    status: # optional, default is ${{ job.status }}
    # Deprecated. Job name included in message title. Same as title input.
    job: # optional
    # Content. Shown as an message outside of the embed. See [Mention to user/role](#mention-to-user-role)
    content: # optional
    # String included in embed title. Overrides job input.
    title: # optional, default is ${{ github.workflow }}
    # Description included in message
    description: # optional
    # Image attached to the message
    image: # optional
    # Overrides Discord embed color
    color: # optional
    # URL to jump when the title is clicked
    url: # optional
    # Overrides Discord webhook username
    username: # optional
    # Overrides Discord webhook avatar url
    avatar_url: # optional
    # This action won't make workflow failed by default.
    nofail: # optional, default is true
    # Suppress GitHub context fields
    nocontext: # optional, default is false
    # Avoid appending job status to title
    noprefix: # optional, default is false
    # Suppress detailed embed fields
    nodetail: # optional, default is false
    # Avoid appending timestamp
    notimestamp: # optional, default is false
          

name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
